AllCops:
  TargetRubyVersion: 2.4.3
  Exclude:
    - deployment/**/*
    - examples/**/*
    - frontend/**/*
    - operator/**/*
    - spec/**/*
    - vendor/**/*
    
Metrics/LineLength:
  Max: 99
Metrics/AbcSize:
  Max: 20