apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitops-access-api
subjects:
  - kind: ServiceAccount
    name: gitops-access-api
    namespace: wunderwander-gitops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
