---
# Source: wunderwander-chart/templates/1_namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wunderwander-gitops

---
# Source: wunderwander-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-access-api
  namespace: wunderwander-gitops

---
# Source: wunderwander-chart/templates/wunderwannder-gitops-crd.yml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gitops.io.wunderwander
  namespace: wunderwander-gitops
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: io.wunderwander
  # list of versions supported by this CustomResourceDefinition
  version: v1
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gitops
    # singular name to be used as an alias on the CLI and for display
    singular: gitop
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GitOp
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - go

---
# Source: wunderwander-chart/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-access-api
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'

---
# Source: wunderwander-chart/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitops-access-api
subjects:
  - kind: ServiceAccount
    name: gitops-access-api
    namespace: wunderwander-gitops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
# Source: wunderwander-chart/templates/deployment_gitops_controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-operator-controller
  namespace: wunderwander-gitops
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: gitops-operator-controller
  template:
    metadata:
      labels:
        app: gitops-operator-controller
    spec:
      serviceAccountName: gitops-access-api
      containers:
        - name: gitops-operator-controller-mainprocess
          image: "foldingbeauty/wunderwander-gitops:0.1.5"
          imagePullPolicy: IfNotPresent
          command: ["ruby"]
          args: ["wunderwander_gitops_operator.rb"]
          env:
            - name: GITOPS_NAMESPACE
              value: wunderwander-gitops
            - name: GITOPS_IMAGE
              value: "foldingbeauty/wunderwander-gitops:0.1.5"
---
# Source: wunderwander-chart/templates/deployment_gitops_ui.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-operator-ui
  namespace: wunderwander-gitops
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: gitops-operator-ui
  template:
    metadata:
      labels:
        app: gitops-operator-ui
    spec:
      serviceAccountName: gitops-access-api
      containers:
        - name: gitops-operator-ui-mainprocess
          image: "foldingbeauty/wunderwander-gitops:0.1.5"
          imagePullPolicy: IfNotPresent
          command: ["ruby"]
          args: ["wunderwander_gitops_frontend.rb"]
          env:
            - name: GITOPS_ENVIRONMENT
              value: production
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3

