# source (0.1.0) = _namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wunderwander-gitops
---
# source (0.1.0) = clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-access-api
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
---
# source (0.1.0) = clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitops-access-api
subjects:
  - kind: ServiceAccount
    name: gitops-access-api
    namespace: wunderwander-gitops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# source (0.1.0) = deployment_gitops_controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-operator-controller
  namespace: wunderwander-gitops
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: gitops-operator-controller
  template:
    metadata:
      labels:
        app: gitops-operator-controller
    spec:
      serviceAccountName: gitops-access-api
      containers:
        - name: gitops-operator-controller-mainprocess
          image: foldingbeauty/wunderwander-gitops:0.1.2-dev
          command: ["ruby"]
          args: ["wunderwander-gitops-operator.rb"]
---
# source (0.1.0) = deployment_gitops_ui.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-operator-ui
  namespace:  wunderwander-gitops
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: gitops-operator-ui
  template:
    metadata:
      labels:
        app: gitops-operator-ui
    spec:
      serviceAccountName: gitops-access-api
      containers:
        - name: gitops-operator-ui-mainprocess
          image: foldingbeauty/wunderwander-gitops:0.1.2-dev
          command: ["ruby"]
          args: ["wunderwander-gitops-frontend.rb"]
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
# source (0.1.0) = serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-access-api
  namespace: wunderwander-gitops
---
# source (0.1.0) = wunderwannder-gitops-crd.yml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gitops.io.wunderwander
  namespace: gitops
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: io.wunderwander
  # list of versions supported by this CustomResourceDefinition
  version: v1
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gitops
    # singular name to be used as an alias on the CLI and for display
    singular: gitop
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GitOp
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - go
---
