apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gitops.io.wunderwander
  namespace: gitops
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: io.wunderwander
  # list of versions supported by this CustomResourceDefinition
  version: v1
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gitops
    # singular name to be used as an alias on the CLI and for display
    singular: gitop
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GitOp
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - go
