apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-operator-controller
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: gitops-operator-controller
  template:
    metadata:
      labels:
        app: gitops-operator-controller
    spec:
      serviceAccountName: gitops-access-api
      containers:
        - name: gitops-operator-controller-mainprocess
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ruby"]
          args: ["wunderwander_gitops_operator.rb"]
          env:
            - name: GITOPS_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: GITOPS_IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
