apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-operator-ui
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: gitops-operator-ui
  template:
    metadata:
      labels:
        app: gitops-operator-ui
    spec:
      serviceAccountName: gitops-access-api
      containers:
        - name: gitops-operator-ui-mainprocess
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ruby"]
          args: ["wunderwander_gitops_frontend.rb"]
          env:
            - name: GITOPS_ENVIRONMENT
              value: production
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
